#!/usr/bin/env sh

if ! command -v nix &> /dev/null
then
  curl -L https://nixos.org/nix/install | sh
fi

sudo rm -f /etc/nix/nix.conf

local_path=$HOME/.config/nixpkgs
$SHELL -ic "if cd $local_path; then git pull; else gh auth login; gh repo clone nix-configuration $local_path; fi"
echo $SHELL -ic 'nix-shell -p git just --command just'
