#!/usr/bin/env bash

sudo launchctl bootout system/org.nixos.nix-daemon
sudo rm /Library/LaunchDaemons/org.nixos.nix-daemon.plist

sudo mv /etc/bashrc.backup-before-nix /etc/bashrc

sudo mv /etc/zshrc.backup-before-nix /etc/zshrc

sudo mv /etc/bash.bashrc.backup-before-nix /etc/bash.bashrc

sudo rm -rf /etc/nix /nix /var/root/.nix-profile /var/root/.nix-defexpr /var/root/.nix-channels /Users/sheelpatel/.nix-profile /Users/sheelpatel/.nix-defexpr /Users/sheelpatel/.nix-channels

